language: java

jdk:
  - oraclejdk8

os:
  - linux

env:
JAVA_8_HOME=/usr/lib/jvm/java-8-oracle

cache:
  directories:
  - $HOME/.m2


install:
 - set -o pipefail
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V